name = "kahn-building-materials"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "kaneshuju"
database_id = "1017f91b-e6f1-42d9-b9c3-5f32904be73a"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "kahn-images"
