name = "kahn-building-materials"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "kaneshuju"
database_id = "1017f91b-e6f1-42d9-b9c3-5f32904be73a"

# R2 存储桶配置 - 图片上传
[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "kaen"

# 本地开发环境配置
[vars]
R2_PUBLIC_DOMAIN = "https://pub-b9f0c2c358074609bf8701513c879957.r2.dev"
JWT_SECRET = "kn-wallpaperglue-jwt-secret-2024-production-key-change-this-in-production"

[env.production]
# D1 数据库配置 - 生产环境
[[env.production.d1_databases]]
binding = "DB"
database_name = "kaneshuju"
database_id = "1017f91b-e6f1-42d9-b9c3-5f32904be73a"

# R2 存储桶配置 - 生产环境
[[env.production.r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "kaen"

[env.production.vars]
ENVIRONMENT = "production"
R2_PUBLIC_DOMAIN = "https://pub-b9f0c2c358074609bf8701513c879957.r2.dev"
JWT_SECRET = "kn-wallpaperglue-jwt-secret-2024-production-key-change-this-in-production"