name = "kahn-building-materials"
compatibility_date = "2024-01-01"

[env.production]
name = "kahn-building-materials"

[build]
command = "pnpm run build"
directory = "dist"

# Environment variables for Cloudflare Pages
# These will be set in the Cloudflare dashboard
# VITE_SUPABASE_URL
# VITE_SUPABASE_ANON_KEY