name = "kahn-building-materials"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[env.production.vars]
VITE_SUPABASE_URL = "https://your-project.supabase.co"
VITE_SUPABASE_ANON_KEY = "your-anon-key"
VITE_API_BASE_URL = "https://your-api.cloudflare.dev"