
CREATE TABLE IF NOT EXISTS seo_configs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  page_key TEXT UNIQUE NOT NULL,
  page_name TEXT,
  title_zh TEXT,
  title_en TEXT,
  title_ru TEXT,
  description_zh TEXT,
  description_en TEXT,
  description_ru TEXT,
  keywords_zh TEXT,
  keywords_en TEXT,
  keywords_ru TEXT,
  geo_region TEXT,
  geo_placename TEXT,
  geo_position TEXT,
  og_title_zh TEXT,
  og_title_en TEXT,
  og_title_ru TEXT,
  og_description_zh TEXT,
  og_description_en TEXT,
  og_description_ru TEXT,
  og_image_url TEXT,
  schema_type TEXT,
  schema_data TEXT,
  is_active INTEGER DEFAULT 1,
  priority INTEGER DEFAULT 1,
  last_updated TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
